### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by mximp**
#3 Add MIT license

### CODE REVIEW

**Comment by mximp** [comment]
@yegor256 please merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by mximp** [comment]
@yegor256 seems there must be access granted to objectionary secrets:
```
.rultor.yml in yegor256/objectionary-secrets doesn't allow objectionary/eo.tmbundle to use its assets (there are 20 friends), see http://doc.rultor.com/reference.html#assets
```

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
